//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "641f87fdbd5d11898d1f0470"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Mest Mestsson",
  "email": "mest@mail.com",
  "password": "mest"
}

###

// LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "mest@mail.com",
  "password": "mest"
}

###

//
// API ENDPOINTS PRODUKTER
//

// HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/64207d36b2d8acfa3b9f02a7 
// ID PÅ PRODUKT

###

// SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Produkt glass",
  "description": "Beskrivning av produkt glass",
  "price": 150, 
  "lager": 30
}

###

//
// API ENDPOINTS ORDERS
//

// SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "641f87fdbd5d11898d1f0470",
      "products": [
    {
      "productId": "642064e1fe7d82d6d125249a",
      "quantity": 2
    },
    {
      "productId": "641f987cd9905449c2d6501d",
      "quantity": 2
    }
  ]
}

###


// HÄMTA ALLA ORDERS
GET http://localhost:3000/api/orders/all/

###